Repository scalar-labs/scalar-terraform, pull requests merged in 2021-04, with the labels that each got.

#300 Fix test parttern to use regex for cassandra jvm.options
  provision/ansible/playbooks/roles/goss/templates/config_validates/cassandra.yaml.j2
Labels: bugfix

#302 Fix expect value of bai for cassandra jvm
  provision/ansible/playbooks/roles/goss/files/config_vars/aws_bai.yaml
  provision/ansible/playbooks/roles/goss/files/config_vars/azure_bai.yaml
Labels: bugfix

#301 Add nr requests for azure cassandra
  provision/ansible/playbooks/roles/cassandra/defaults/main.yml
  provision/ansible/playbooks/roles/goss/files/config_vars/azure_bai.yaml
  provision/ansible/playbooks/roles/goss/files/config_vars/azure_default.yaml
Labels: bugfix

#303 Remove triggers of cassandra from scalardl module
  modules/aws/cassandra/README.md
  modules/aws/cassandra/output.tf
  modules/aws/scalardl/cluster/README.md
  modules/aws/scalardl/cluster/main.tf
  modules/aws/scalardl/cluster/vars.tf
  modules/aws/scalardl/envoy.tf
  modules/aws/scalardl/locals.tf
  modules/aws/scalardl/scalardl.tf
  modules/aws/scalardl/vars.tf
  modules/azure/cassandra/README.md
  modules/azure/cassandra/output.tf
  modules/azure/scalardl/cluster/README.md
  modules/azure/scalardl/cluster/main.tf
  modules/azure/scalardl/cluster/vars.tf
  modules/azure/scalardl/envoy.tf
  modules/azure/scalardl/locals.tf
  modules/azure/scalardl/scalardl.tf
  modules/azure/scalardl/vars.tf
  modules/universal/scalardl/main.tf
  modules/universal/scalardl/vars.tf
Labels: improvement

#293 Add Scalar Auditor deployment support to scalardl module
  modules/aws/scalardl/cluster/README.md
  modules/aws/scalardl/cluster/main.tf
  modules/aws/scalardl/cluster/vars.tf
  modules/aws/scalardl/locals.tf
  modules/aws/scalardl/scalardl.tf
  modules/azure/scalardl/cluster/README.md
  modules/azure/scalardl/cluster/main.tf
  modules/azure/scalardl/cluster/vars.tf
  modules/azure/scalardl/locals.tf
  modules/azure/scalardl/scalardl.tf
  modules/universal/scalardl/main.tf
  modules/universal/scalardl/provision/docker-compose.yml
  modules/universal/scalardl/vars.tf
Labels: enhancement

#304 Update readme for scalardl module
  modules/aws/scalardl/README.md
  modules/azure/scalardl/README.md
Labels: bugfix
