Repository scalar-labs/scalar-terraform, pull requests merged in 2021-02, with the labels that each got.

#272 Fix autoscale in azure k8s
  modules/azure/kubernetes/kubernetes.tf
Labels: bugfix

#275 Fix default autoscaling group bug in aks
  modules/azure/kubernetes/kubernetes.tf
Labels: bugfix

#277 Fix deprecated property in azuread_application
  modules/azure/kubernetes/kubernetes.tf
Labels: improvement

#274 Specify cluster accessibility simply for eks
  modules/aws/kubernetes/cluster.tf
  modules/aws/kubernetes/locals.tf
Labels: improvement

#273 Able to configure cluster accessibility for aks
  modules/azure/kubernetes/kubernetes.tf
  modules/azure/kubernetes/locals.tf
Labels: improvement

#276 Add cluster autoscaler for eks
  modules/aws/kubernetes/autoscaler.tf
  modules/aws/kubernetes/autoscaler/README.md
  modules/aws/kubernetes/autoscaler/iam.tf
  modules/aws/kubernetes/autoscaler/main.tf
  modules/aws/kubernetes/autoscaler/vars.tf
  modules/aws/kubernetes/locals.tf
Labels: enhancement

#280 Remove unused mount point for tailon container
  modules/universal/monitor/provision/docker-compose.yml
Labels: improvement

#279 Move AKSScalarTerraformDeploymentGuide.md from scalar-kubernetes
  docs/AKSScalarTerraformDeploymentGuide.md
  docs/CloudPrivileges.md
  docs/images/architecture-aks.png
Labels: documentation

#283 Add base for network module
  modules/aws/network/locals.tf
  modules/aws/network/vars.tf
  modules/azure/network/locals.tf
  modules/azure/network/vars.tf
Labels: enhancement

#282 Add goss ansible role
  provision/ansible/playbooks/goss-server.yml
  provision/ansible/playbooks/roles/goss/defaults/main.yml
  provision/ansible/playbooks/roles/goss/files/config_validates/cassandra.yaml
  provision/ansible/playbooks/roles/goss/files/config_validates/common.yaml
  provision/ansible/playbooks/roles/goss/files/config_vars/aws_bai.yaml
  provision/ansible/playbooks/roles/goss/files/config_vars/aws_default.yaml
  provision/ansible/playbooks/roles/goss/files/config_vars/azure_bai.yaml
  provision/ansible/playbooks/roles/goss/files/config_vars/azure_default.yaml
  provision/ansible/playbooks/roles/goss/files/goss.yaml
  provision/ansible/playbooks/roles/goss/tasks/install.yml
  provision/ansible/playbooks/roles/goss/tasks/main.yml
  provision/ansible/playbooks/roles/goss/tasks/test.yml
Labels: enhancement

#286 Fix bug for aws network base
  modules/aws/network/README.md
  modules/aws/network/locals.tf
  modules/azure/network/README.md
Labels: bugfix
