Repository scalar-labs/scalar-terraform, pull requests merged in 2021-05, with the labels that each got.

#309 Fix logrotate issue in monitor server
  provision/ansible/playbooks/roles/td-agent_aggregation/templates/monitor.logrotate.j2
Labels: bugfix

#308 Update troubleshooting guide
  docs/TroubleshootingGuide.md
Labels: bugfix

#310 Fix to copy schema loader image via bastion
  modules/universal/scalardl/main.tf
Labels: bugfix

#311 Add retry for get rpm key in td-agent ansible role
  provision/ansible/playbooks/roles/td-agent/tasks/setup-redhat.yml
Labels: improvement

#313 Set context to allow logrotate for aggregated logs
  provision/ansible/playbooks/roles/td-agent_aggregation/tasks/main.yml
Labels: bugfix

#314 Add create release draft workflow
  .github/release-drafter.yml
  .github/workflows/release_drafter.yml
Labels: enhancement

#316 Fix terraform refresh in docs
  docs/HowToExpandAzureManagedDisk.md
  docs/HowToExpandEBS.md
  docs/ShareEnvironment.md
Labels: documentation
