Repository scalar-labs/scalar-terraform, pull requests merged in 2021-03, with the labels that each got.

#287 Update docs for upgrade terraform to 0.14
  docs/AKSScalarTerraformDeploymentGuide.md
  docs/GettingStarted.md
  docs/MonitorGuide.md
  docs/SSHGuide.md
Labels: documentation, enhancement

#278 Add EKS Guide
  docs/EKSDeploymentSidenote.md
  docs/EKSScalarTerraformDeploymentGuide.md
  docs/images/architecture-eks.png
Labels: documentation

#288 Fix scalardl instance size for aws chiku
  modules/aws/scalardl/locals.tf
Labels: improvement

#290 Upgrade k8s version to 1.19
  modules/aws/kubernetes/locals.tf
  modules/azure/kubernetes/README.md
  modules/azure/kubernetes/kubernetes.tf
  modules/azure/kubernetes/locals.tf
Labels: enhancement

#291 Fix output inventory bug
  modules/aws/network/locals.tf
  modules/azure/network/locals.tf
Labels: bugfix

#292 Fix resource group not found issue
  modules/azure/network/main.tf
Labels: bugfix

#297 Add disk io params for goss
  provision/ansible/playbooks/roles/goss/defaults/main.yml
  provision/ansible/playbooks/roles/goss/files/config_validates/cassandra.yaml
  provision/ansible/playbooks/roles/goss/files/config_vars/aws_bai.yaml
  provision/ansible/playbooks/roles/goss/files/config_vars/aws_default.yaml
  provision/ansible/playbooks/roles/goss/files/config_vars/azure_bai.yaml
  provision/ansible/playbooks/roles/goss/files/config_vars/azure_default.yaml
  provision/ansible/playbooks/roles/goss/tasks/test.yml
  provision/ansible/playbooks/roles/goss/templates/config_validates/cassandra.yaml.j2
Labels: enhancement

#296 Set disk scheduler for cassandra
  provision/ansible/playbooks/roles/cassandra/defaults/main.yml
  provision/ansible/playbooks/roles/cassandra/files/disk_io_params.service
  provision/ansible/playbooks/roles/cassandra/tasks/main.yml
  provision/ansible/playbooks/roles/cassandra/tasks/setup_disk_io_params.yml
  provision/ansible/playbooks/roles/cassandra/templates/disk_io_params.sh.j2
Labels: enhancement

#299 Fix Envoy auto_gen_cert script
  modules/aws/scalardl/locals.tf
  modules/azure/scalardl/locals.tf
  modules/universal/envoy/main.tf
  modules/universal/envoy/provision/auto_gen_cert.sh
  modules/universal/envoy/vars.tf
Labels: bugfix
